export type ConnectionStatus = "pending" | "accepted" | "declined";

export type ConnectionRequest = {
  uid: string;
  name: string;
  initials: string;
  useInitials: boolean;
  location: string;
  age: number;
  gender: "Pria" | "Wanita";
  requestedAt: string;
  message: string;
  status: ConnectionStatus;
  cv: {
    birth: string;
    religion: string;
    maritalStatus: string;
    education: string;
    job: string;
    height: string;
    weight: string;
    about: string;
    marriageVision: string;
    partnerExpectation: string;
    marriageTarget: string;
  };
  visibleFields: string[];
};

export const CONNECTION_STATUS_STORAGE_KEY = "onyou-connection-status-v1";

const sharedVisibleFields = ["name", "birth", "location", "religion", "maritalStatus", "education", "job", "height", "weight", "about", "marriageVision", "partnerExpectation", "marriageTarget"];

export const CONNECTION_REQUESTS: ConnectionRequest[] = [
  { uid:"aulia-s", name:"Aulia Safitri", initials:"AS", useInitials:true, location:"Bandung, Jawa Barat", age:28, gender:"Wanita", requestedAt:"7 September 2026", message:"Assalamu’alaikum, saya tertarik dengan cara Anda memandang keluarga dan pernikahan. Jika berkenan, saya ingin saling mengenal dengan proses yang baik dan terarah.", status:"pending", cv:{birth:"Bandung, 18 April 1998",religion:"Islam",maritalStatus:"Belum pernah menikah",education:"S1 Psikologi",job:"People Development Specialist",height:"160 cm",weight:"50 kg",about:"Pribadi yang hangat, suka belajar, dan dekat dengan keluarga.",marriageVision:"Membangun keluarga yang tenang, saling mendukung, dan bertumbuh dalam nilai agama.",partnerExpectation:"Komunikatif, bertanggung jawab, dan siap melibatkan keluarga.",marriageTarget:"Dalam 1–2 tahun"}, visibleFields:sharedVisibleFields },
  { uid:"rizky-a", name:"Rizky Ananda", initials:"RA", useInitials:false, location:"Surabaya, Jawa Timur", age:31, gender:"Pria", requestedAt:"6 September 2026", message:"Halo, saya merasa visi keluarga kita memiliki beberapa kesamaan. Saya ingin membuka komunikasi dengan niat serius apabila Anda juga merasa nyaman.", status:"pending", cv:{birth:"Surabaya, 9 Januari 1995",religion:"Islam",maritalStatus:"Belum pernah menikah",education:"S1 Manajemen",job:"Pengusaha kuliner",height:"175 cm",weight:"71 kg",about:"Tenang, mandiri, dan senang menghabiskan waktu bersama keluarga.",marriageVision:"Menjadi pasangan yang saling menjaga, terbuka, dan bertumbuh bersama.",partnerExpectation:"Dewasa, hangat, dan memiliki tujuan keluarga yang jelas.",marriageTarget:"Dalam 2 tahun"}, visibleFields:sharedVisibleFields },
  { uid:"nadia-p", name:"Nadia Putri", initials:"NP", useInitials:true, location:"Yogyakarta, DI Yogyakarta", age:27, gender:"Wanita", requestedAt:"5 September 2026", message:"Salam kenal. Saya menghargai profil Anda yang terbuka dan jelas. Jika Anda berkenan, saya ingin mengenal nilai serta rencana keluarga Anda lebih jauh.", status:"pending", cv:{birth:"Sleman, 22 Juli 1999",religion:"Islam",maritalStatus:"Belum pernah menikah",education:"S2 Pendidikan",job:"Dosen",height:"158 cm",weight:"48 kg",about:"Suka membaca, mengajar, dan menikmati percakapan yang bermakna.",marriageVision:"Rumah tangga yang menjadi ruang aman untuk belajar dan beribadah.",partnerExpectation:"Jujur, sabar, dan menghargai pendidikan.",marriageTarget:"Dalam 1–3 tahun"}, visibleFields:sharedVisibleFields },
  { uid:"fajar-m", name:"Fajar Maulana", initials:"FM", useInitials:true, location:"Makassar, Sulawesi Selatan", age:30, gender:"Pria", requestedAt:"4 September 2026", message:"Assalamu’alaikum. Domisili dan tujuan pernikahan kita tampaknya sejalan. Saya ingin memperkenalkan diri dengan baik dan melanjutkan melalui keluarga bila cocok.", status:"pending", cv:{birth:"Makassar, 3 Maret 1996",religion:"Islam",maritalStatus:"Belum pernah menikah",education:"S1 Teknik Sipil",job:"Project Engineer",height:"172 cm",weight:"68 kg",about:"Teratur, pekerja keras, dan menyukai kegiatan luar ruang.",marriageVision:"Membangun keluarga yang kompak dengan komunikasi dan pembagian peran yang sehat.",partnerExpectation:"Sederhana, terbuka, dan dekat dengan keluarga.",marriageTarget:"Dalam 1 tahun"}, visibleFields:sharedVisibleFields },
  { uid:"salsa-n", name:"Salsabila Nirmala", initials:"SN", useInitials:false, location:"Jakarta Selatan, DKI Jakarta", age:29, gender:"Wanita", requestedAt:"3 September 2026", message:"Halo, cara Anda menjelaskan kesiapan emosional menarik perhatian saya. Saya ingin bertukar pandangan dan melihat apakah nilai kita dapat berjalan searah.", status:"pending", cv:{birth:"Jakarta, 11 November 1997",religion:"Islam",maritalStatus:"Belum pernah menikah",education:"S1 Ilmu Komunikasi",job:"Brand Strategist",height:"162 cm",weight:"52 kg",about:"Kreatif, reflektif, dan menyukai keseimbangan antara karier dan keluarga.",marriageVision:"Pernikahan yang bertumpu pada persahabatan, kejujuran, dan rasa aman.",partnerExpectation:"Stabil secara emosi dan terbiasa berdiskusi.",marriageTarget:"Dalam 2 tahun"}, visibleFields:sharedVisibleFields },
  { uid:"dimas-h", name:"Dimas Haryanto", initials:"DH", useInitials:true, location:"Semarang, Jawa Tengah", age:32, gender:"Pria", requestedAt:"2 September 2026", message:"Salam kenal. Saya melihat ada kesamaan dalam pandangan mengenai keuangan dan tanggung jawab keluarga. Semoga kita dapat berdiskusi lebih lanjut.", status:"pending", cv:{birth:"Semarang, 20 Mei 1994",religion:"Islam",maritalStatus:"Belum pernah menikah",education:"S1 Akuntansi",job:"Financial Analyst",height:"178 cm",weight:"74 kg",about:"Praktis, tenang, dan senang merencanakan masa depan.",marriageVision:"Membangun keluarga yang transparan, stabil, dan saling menghargai.",partnerExpectation:"Bijaksana, komunikatif, dan memiliki empati.",marriageTarget:"Dalam 1–2 tahun"}, visibleFields:sharedVisibleFields },
  { uid:"putri-r", name:"Putri Rahma", initials:"PR", useInitials:true, location:"Malang, Jawa Timur", age:26, gender:"Wanita", requestedAt:"1 September 2026", message:"Assalamu’alaikum, profil Anda terasa tulus dan mudah dipahami. Saya ingin menyampaikan niat berkenalan secara serius dengan batasan yang nyaman bagi kita berdua.", status:"pending", cv:{birth:"Malang, 7 Agustus 2000",religion:"Islam",maritalStatus:"Belum pernah menikah",education:"S1 Farmasi",job:"Apoteker",height:"159 cm",weight:"49 kg",about:"Ramah, teliti, dan senang mencoba resep baru.",marriageVision:"Rumah tangga yang hangat, sehat, dan saling menguatkan.",partnerExpectation:"Penyayang, konsisten, dan bertanggung jawab.",marriageTarget:"Dalam 2–3 tahun"}, visibleFields:sharedVisibleFields },
  { uid:"bagas-k", name:"Bagas Kurnia", initials:"BK", useInitials:false, location:"Bogor, Jawa Barat", age:29, gender:"Pria", requestedAt:"31 Agustus 2026", message:"Halo, saya tertarik dengan minat dan nilai keluarga yang Anda bagikan. Jika cocok, saya berharap proses perkenalan ini dapat berjalan jelas dan saling menghargai.", status:"pending", cv:{birth:"Bogor, 14 Desember 1997",religion:"Islam",maritalStatus:"Belum pernah menikah",education:"S1 Informatika",job:"Software Engineer",height:"173 cm",weight:"69 kg",about:"Penasaran, humoris, dan menikmati kegiatan bersama orang terdekat.",marriageVision:"Menjadi tim yang saling mendukung tujuan pribadi dan keluarga.",partnerExpectation:"Terbuka, mandiri, dan mau belajar bersama.",marriageTarget:"Dalam 2 tahun"}, visibleFields:sharedVisibleFields },
  { uid:"intan-l", name:"Intan Lestari", initials:"IL", useInitials:true, location:"Denpasar, Bali", age:30, gender:"Wanita", requestedAt:"30 Agustus 2026", message:"Salam kenal. Saya menghargai keterbukaan Anda tentang rencana tempat tinggal. Saya ingin mengenal cara pandang kita terhadap keluarga lebih jauh.", status:"pending", cv:{birth:"Denpasar, 2 Februari 1996",religion:"Islam",maritalStatus:"Belum pernah menikah",education:"S1 Arsitektur",job:"Interior Designer",height:"164 cm",weight:"53 kg",about:"Mandiri, detail, dan menyukai seni serta perjalanan singkat.",marriageVision:"Menciptakan rumah yang damai dengan komunikasi yang sehat.",partnerExpectation:"Menghargai perbedaan dan mampu membuat keputusan bersama.",marriageTarget:"Dalam 1–2 tahun"}, visibleFields:sharedVisibleFields },
  { uid:"arief-s", name:"Arief Setiawan", initials:"AS", useInitials:true, location:"Medan, Sumatera Utara", age:33, gender:"Pria", requestedAt:"29 Agustus 2026", message:"Assalamu’alaikum. Saya ingin berkenalan karena melihat kesamaan dalam target dan persiapan menikah. Semoga niat baik ini dapat kita pertimbangkan bersama.", status:"pending", cv:{birth:"Medan, 26 Juni 1993",religion:"Islam",maritalStatus:"Belum pernah menikah",education:"S2 Administrasi Bisnis",job:"Operations Manager",height:"176 cm",weight:"73 kg",about:"Tegas, hangat, dan terbiasa bertanggung jawab dalam keluarga.",marriageVision:"Keluarga yang memiliki arah, rasa aman, dan ruang berkembang.",partnerExpectation:"Dewasa, suportif, dan menyukai komunikasi langsung.",marriageTarget:"Dalam 1 tahun"}, visibleFields:sharedVisibleFields },
  { uid:"maya-f", name:"Maya Fitriani", initials:"MF", useInitials:true, location:"Palembang, Sumatera Selatan", age:28, gender:"Wanita", requestedAt:"28 Agustus 2026", message:"Halo, profil Anda memberikan gambaran yang jujur. Saya ingin mengenal lebih jauh dengan niat serius dan proses yang tetap melibatkan keluarga.", status:"pending", cv:{birth:"Palembang, 17 Oktober 1998",religion:"Islam",maritalStatus:"Belum pernah menikah",education:"S1 Keperawatan",job:"Perawat",height:"157 cm",weight:"48 kg",about:"Peduli, sabar, dan senang membantu orang lain.",marriageVision:"Tumbuh menjadi pasangan yang saling merawat dan mengingatkan.",partnerExpectation:"Tenang, setia, dan menghargai pekerjaan pasangan.",marriageTarget:"Dalam 2 tahun"}, visibleFields:sharedVisibleFields },
  { uid:"yusuf-r", name:"Yusuf Ramadhan", initials:"YR", useInitials:false, location:"Depok, Jawa Barat", age:30, gender:"Pria", requestedAt:"27 Agustus 2026", message:"Salam kenal. Saya tertarik dengan visi pernikahan yang Anda sampaikan dan ingin berdiskusi lebih lanjut dengan cara yang baik serta saling menghormati.", status:"pending", cv:{birth:"Depok, 5 April 1996",religion:"Islam",maritalStatus:"Belum pernah menikah",education:"S1 Hukum",job:"Legal Counsel",height:"174 cm",weight:"70 kg",about:"Terbuka, analitis, dan menghargai komitmen.",marriageVision:"Pernikahan sebagai kemitraan yang adil dan penuh kepercayaan.",partnerExpectation:"Jujur, berempati, dan siap membangun keputusan bersama.",marriageTarget:"Dalam 1–2 tahun"}, visibleFields:sharedVisibleFields },
  { uid:"citra-a", name:"Citra Anjani", initials:"CA", useInitials:true, location:"Balikpapan, Kalimantan Timur", age:27, gender:"Wanita", requestedAt:"26 Agustus 2026", message:"Assalamu’alaikum, saya ingin membuka komunikasi karena merasa beberapa prinsip kita sejalan. Tidak perlu terburu-buru, saya berharap kita dapat saling mengenal dengan nyaman.", status:"pending", cv:{birth:"Balikpapan, 12 September 1999",religion:"Islam",maritalStatus:"Belum pernah menikah",education:"S1 Ekonomi",job:"Business Analyst",height:"161 cm",weight:"51 kg",about:"Optimis, terorganisir, dan dekat dengan keluarga.",marriageVision:"Membangun kehidupan yang seimbang antara keluarga, ibadah, dan karya.",partnerExpectation:"Punya arah hidup, lembut, dan dapat dipercaya.",marriageTarget:"Dalam 2–3 tahun"}, visibleFields:sharedVisibleFields },
];

export function getConnectionRequest(uid: string) {
  return CONNECTION_REQUESTS.find((request) => request.uid === uid);
}

export function getDisplayName(request: ConnectionRequest) {
  return request.useInitials ? request.initials : request.name;
}
